### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by kbmanikanta** [voltraco/localstorage#1]
Hi,
I am getting the following error. can you please help me?

    this._store = window.localStorage
                  ^
ReferenceError: window is not defined
    at new LocalStorage (C:\Live\quickstart\node\node_modules\localstorage\index.js:4:19)
    at Object.<anonymous> (C:\Live\quickstart\node\index.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by monojack** [comment]
Are you trying to use it in Node?

**Comment by heapwolf** [comment]
oh yeah, this is a browser-side module. Were you hoping to find an isomorphic localstorage solution? if so, would be open to a PR that somehow allowed that.
